csharp/Esynctraining/AC/Esynctraining.AC.Web/Controllers/ScoBrowserController.cs
namespace eSyncTraining.Web.Controllers
{
    using System.Collections.Generic;
    using System.Linq;
    using System.Web.Mvc;

    using Esynctraining.AC.Provider.DataObjects.Results;
    using Esynctraining.AC.Provider.Entities;
    using eSyncTraining.Web.Extenstions;
    using eSyncTraining.Web.Models;

    /// <summary>
    /// The sco browser controller.
    /// </summary>
    public class ScoBrowserController : AdobeConnectedControllerBase
    {
        /// <summary>
        /// The browse.
        /// </summary>
        /// <param name="scoType">
        /// The sco type.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult Browse(string scoType)
        {
            ScoBrowserModel model = null;

            if (!string.IsNullOrWhiteSpace(scoType) && this.LoginWithSession().Success)
            {
                var result = this.AdobeConnect.GetContentsByType(scoType);

                model = new ScoBrowserModel
                        {
                            Values = GetContents(result),
                            ScoType = scoType,
                            FolderId = result.ScoId
                        };
            }

            return this.View(model);
        }

        public ActionResult BrowseFolder(string scoType, string folderId)
        {
            ScoBrowserModel model = null;

            if (!string.IsNullOrWhiteSpace(folderId) && this.LoginWithSession().Success)
            {
                var result = this.AdobeConnect.GetContentsByScoId(folderId);

                model = new ScoBrowserModel
                        {
                            Values = GetContents(result),
                            ScoType = scoType,
                            FolderId = result.ScoId
                        };
            }

            return this.View("Browse", model);
        }

        #region Helpers

        /// <summary>
        /// The get contents.
        /// </summary>
        /// <param name="getter">
        /// The getter.
        /// </param>
        /// <returns>
        /// Collection of Models.
        /// </returns>
        private static IEnumerable<ScoContentModel> GetContents(GenericCollectionResultBase<ScoContent> result)
        {
            return result.Success && result.Values != null
                       ? result.Values.Select(item => item.ToModel()).ToArray()
                       : Enumerable.Empty<ScoContentModel>();
        }

        #endregion

        public ActionResult Create(string scoType, string folderId)
        {
            if (scoType.EndsWith("meetings"))
            {
                return this.RedirectToAction("Create", "MeetingUpdate", new { folderId, returnUrl = this.ReferrerUrl });
            }
            else if (scoType.EndsWith("events"))
            {
                {
                    return this.RedirectToAction("Create", "EventUpdate", new { folderId, returnUrl = this.ReferrerUrl });
                }
            }

            return this.RedirectToLocal(this.ReferrerUrl);
        }

        /// <summary>
        /// The edit item.
        /// </summary>
        /// <param name="scoType">
        /// The sco Type.
        /// </param>
        /// <param name="scoId">
        /// The sco Id.
        /// </param>
        /// <returns>
        /// The <see cref="ActionResult"/>.
        /// </returns>
        public ActionResult EditItem(string scoType, string scoId)
        {
            object values = null;

            if (scoType.EndsWith("meetings"))
            {
                values = new { id = scoId, returnUrl = this.ReferrerUrl };

                return this.RedirectToAction("Edit", "MeetingUpdate", values);
            }
            else if (scoType.EndsWith("events"))
            {
                values = new { id = scoId, returnUrl = this.ReferrerUrl };

                return this.RedirectToAction("Edit", "EventUpdate", values);
            }

            return this.RedirectToLocal(this.ReferrerUrl);
        }
    }
}

csharp/Esynctraining/AC/Esynctraining.AC.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <title>@ViewBag.Title - eSync To Adobe Connect</title>
        <link href="~/favicon.ico" rel="shortcut icon" type="image/x-icon" />
        <meta name="viewport" content="width=device-width" />
        @Styles.Render("~/Content/css")
        @Scripts.Render("~/bundles/modernizr")
    </head>
    <body>
        <header>
            <div class="content-wrapper">
                <div class="float-left">
                    <p class="site-title">@Html.ActionLink("eSync To Adobe Connect", "Index", "Home")</p>
                </div>
                <div class="float-right">
                    <section id="login">
                        @Html.Partial("_LoginPartial")
                    </section>
                    <nav>
                        <ul id="menu">
                            <li>@Html.ActionLink("Home", "Index", "Home")</li>
                            <li>@Html.ActionLink("User Info", "UserInfo", "Home")</li>
                            <li>@Html.ActionLink("My Events", "MyEvents", "Home")</li>
                            <li>@Html.ActionLink("Sco Browser", "Browse", "ScoBrowser")</li>
                        </ul>
                    </nav>
                </div>
            </div>
        </header>
        <div id="body">
            @RenderSection("featured", required: false)
            <section class="content-wrapper main-content clear-fix">
                @RenderBody()
            </section>
        </div>
        <footer>
            <div class="content-wrapper">
                <div class="float-left">
                    <p>&copy; @DateTime.Now.Year - eSyncTraining</p>
                </div>
            </div>
        </footer>

        @Scripts.Render("~/bundles/jquery")
        @RenderSection("scripts", required: false)
    </body>
</html>

csharp/Esynctraining/AC/Esynctraining.AC.Web/Views/Shared/_ScoUpdateFieldsetPartial.cshtml
@model eSyncTraining.Web.Models.ScoDetailModelBase

@{
    var languagesDropdownContent = new[]
                                       {
                                           new SelectListItem{Text = "English", Value = "en"},
                                           new SelectListItem{Text = "French", Value = "fr"},
                                           new SelectListItem{Text = "German", Value = "de"},
                                           new SelectListItem{Text = "Japanese", Value = "ja"},
                                           new SelectListItem{Text = "Korean", Value = "ko"},
                                           new SelectListItem{Text = "Russian", Value = "ru"}
                                       };

    if (Model != null)
    {
        var selectedLanguage = languagesDropdownContent.FirstOrDefault(p => p.Value.Equals(Model.Language, StringComparison.InvariantCultureIgnoreCase));

        if (selectedLanguage != null)
        {
            selectedLanguage.Selected = true;
        }
    }
}

@if (!string.IsNullOrWhiteSpace(Model.ScoId))
{
    <div class="display-label">
        @Html.DisplayNameFor(model => model.ScoId): @Html.DisplayFor(model => model.ScoId)
        @Html.HiddenFor(model => model.ScoId)
    </div>
}

<div class="display-label">
    @Html.DisplayNameFor(model => model.FolderId): @Html.DisplayFor(model => model.FolderId)
    @Html.HiddenFor(model => model.FolderId)
</div>
        
@if (!string.IsNullOrWhiteSpace(Model.ScoId))
{
    <div class="display-label">
        @Html.DisplayNameFor(model => model.DateCreated): @Html.DisplayFor(model => model.DateCreated)
    </div>

    <div class="display-label">
        @Html.DisplayNameFor(model => model.DateModified): @Html.DisplayFor(model => model.DateModified)
    </div>
}
        
<div>&nbsp;</div>

<div class="editor-label">
    @Html.LabelFor(model => model.UrlPath)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.UrlPath)
    @Html.ValidationMessageFor(model => model.UrlPath)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Name)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.Name)
    @Html.ValidationMessageFor(model => model.Name)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Description)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.Description)
    @Html.ValidationMessageFor(model => model.Description)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.Language)
</div>
<div class="editor-field">
    @Html.DropDownListFor(model => model.Language, languagesDropdownContent)
    @Html.ValidationMessageFor(model => model.Language)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.BeginDate)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.BeginDate)
    @Html.ValidationMessageFor(model => model.BeginDate)
</div>

<div class="editor-label">
    @Html.LabelFor(model => model.EndDate)
</div>
<div class="editor-field">
    @Html.EditorFor(model => model.EndDate)
    @Html.ValidationMessageFor(model => model.EndDate)
</div>

csharp/Esynctraining/AC/Esynctraining.AC.Web/Views/Shared/_UserInfoPartial.cshtml
@{
    ViewBag.Title = "_UserInfoPartial";
}

Hello, my friend.